### ISSUE TITLE
Unknown instruction: ./VENDOR/BIN/LUYA

### ISSUE THREAD

**Issue by vilkh3m** [dev7ch/luya-cms-docker#5]
Hi 

I follow instruction but i dog this error:
```
luya-cms-docker git:(master) docker build .
Sending build context to Docker daemon 89.09 kB
Error response from daemon: Unknown instruction: ./VENDOR/BIN/LUYA
```

i try install this on macOS Sierra 10.12.1
with docker v1.12.3

thx for any help

**Comment by dev7ch** [comment]
Hi, thanks for your input ...
currently this repo is under development and a lot of changes needs to be done.

I ll come back to you if i get this working properly ..
or you have been able to fix it?

Best wishes
